// Focused naval UI test: the 3D iframe is stubbed; authentication, API and SSE are real.
const {chromium}=require('playwright');const path=require('node:path');const assert=require('node:assert/strict');
(async()=>{const {createApp}=await import('../server/server.mjs');const {server}=createApp({file:path.resolve('.runtime/naval-'+Date.now()+'.json')});await new Promise(r=>server.listen(8791,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});const errors=[];
try{const a=await browser.newContext({viewport:{width:1440,height:1000}}),b=await browser.newContext();const pa=await a.newPage(),pb=await b.newPage();
for(const [p,id] of [[pa,'a'],[pb,'b']]){p.on('pageerror',e=>errors.push(e.message));await p.route('**/game/index.html',r=>r.fulfill({contentType:'text/html',body:'<script>parent.togetherBridge.ready()</script>'}));await p.goto('http://127.0.0.1:8791');await p.locator('button[value="'+id+'"]').click();await p.locator('#loading').waitFor({state:'hidden'});await p.getByRole('button',{name:'海戰棋',exact:true}).click();}
await pa.locator('#modal').screenshot({path:'screenshots/naval-lobby.png'});await pa.locator('#new-game').click();await pa.locator('[data-deploy="35"]').click();assert.ok(await pa.locator('#place-ships').isDisabled());await pa.locator('[data-deploy="0"]').click();await pa.locator('#rotate-fleet').click();assert.ok(await pa.locator('#place-ships').isDisabled());await pa.locator('#rotate-fleet').click();assert.ok(await pa.locator('#place-ships').isEnabled());await pa.locator('#modal').screenshot({path:'screenshots/naval-deployment.png'});
await pa.locator('#place-ships').click();await pb.locator('#place-ships').click();
for(const [hit,miss] of [[0,5],[1,11],[2,17]]){await pa.locator('[data-fire="'+hit+'"]:not(:disabled)').click();if(hit===2){await pa.waitForFunction(()=>document.querySelector('.battle-announcement')?.textContent.includes('沉沒'));await pa.locator('#modal').screenshot({path:'screenshots/naval-sinking.png'});}await pb.locator('[data-fire="'+miss+'"]:not(:disabled)').click();}
const s=await pa.evaluate(async()=>await(await fetch('/api/state')).json());assert.deepEqual(s.game.enemySunk,[[0,1,2]]);assert.equal(s.game.enemyBoard,undefined);
await pa.setViewportSize({width:390,height:844});await pa.locator('#modal').screenshot({path:'screenshots/naval-mobile.png'});assert.ok(await pa.evaluate(()=>{const m=document.getElementById('modal');return m.scrollWidth<=m.clientWidth+1;}));
await pb.reload();await pb.locator('#loading').waitFor({state:'hidden'});await pb.getByRole('button',{name:'海戰棋',exact:true}).click();assert.equal(await pb.locator('.own-sea .sunk').count(),3);assert.deepEqual(errors,[]);console.log('PASS naval UI: deployment validation, rotation, ship shapes, sinking animation, hidden fleet, reconnect, 390px layout');
}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
