'use strict';
let fleetSelected=0, fleetGame='', battlePending=false, battleSeen='', battleCounts={own:0,incoming:0},battleEffect=null;
const fleetNames=['晨光巡洋艦','海風護衛艦','星辰巡邏艦'];
const fleetCells=(s,i)=>Array.from({length:[3,2,2][i]},(_,n)=>(s.y+(s.direction==='v'?n:0))*6+s.x+(s.direction==='h'?n:0));
function fleetValid(list){const seen=new Set();return list.every((s,i)=>Number.isInteger(s.x)&&Number.isInteger(s.y)&&s.x>=0&&s.y>=0&&s.x+(s.direction==='h'?[3,2,2][i]:1)<=6&&s.y+(s.direction==='v'?[3,2,2][i]:1)<=6&&fleetCells(s,i).every(c=>{if(seen.has(c))return false;seen.add(c);return true;}));}
function randomFleet(){const result=[];for(let i=0;i<3;i++){for(let tries=0;tries<1000;tries++){const s={x:Math.floor(Math.random()*6),y:Math.floor(Math.random()*6),direction:Math.random()<.5?'h':'v'};if(fleetValid([...result,s])){result.push(s);break;}}}return result.length===3?result:ships;}
const seaCoord=c=>String.fromCharCode(65+c%6)+(Math.floor(c/6)+1);
function shipArt(){return '<span class="vessel" aria-hidden="true"><i class="vessel-cabin"></i><i class="vessel-mast"></i><i class="vessel-port"></i></span>';}
async function battleAction(action,data){if(battlePending)return;battlePending=true;gameView();try{await api(action,data);}catch(e){toast(e.message);}finally{battlePending=false;if(view==='battleship')gameView();}}
function gameView(){
 title('海戰俱樂部','TOGETHER / NAVAL CLUB');const g=state.game,my=state.user.id;
 const container=$('modal-content');container.classList.toggle('naval-deploy',g?.status==='setup');
 if(!g){container.innerHTML=`<div class="naval-lobby"><div class="naval-illustration" aria-hidden="true"><div class="lobby-ship">${shipArt()}</div><span class="sea-ring r1"></span><span class="sea-ring r2"></span><span class="compass">N<br>＋</span></div><div><span class="naval-eyebrow">一張海圖，兩位艦長</span><h3>把小艦隊藏好，<br>一起出航。</h3><p>部署三艘船，輪流探索對方的 6 × 6 海域。命中、落水、擊沉，每一步都有新的線索。</p><ol class="naval-rules"><li>點選海圖部署，可旋轉船艦</li><li>每回合射擊一次，命中也會換手</li><li>先擊沉對方三艘船就獲勝</li></ol><button id="new-game" class="primary" ${battlePending?'disabled':''}>${battlePending?'正在建立…':'建立雙人對局 →'}</button><p class="small">完整對局：勝方 45、另一方 35 金幣。中途投降不發獎勵。</p></div></div>`;$('new-game').onclick=()=>battleAction('game/new',{});return;}
 if(fleetGame!==g.id){fleetGame=g.id;fleetSelected=0;ships=[{x:0,y:0,direction:'h'},{x:0,y:2,direction:'h'},{x:3,y:4,direction:'v'}];}
 if(battleSeen!==g.id){battleSeen=g.id;battleCounts={own:g.ownShots.length,incoming:g.incoming.length};battleEffect=null;}
 else {for(const [key,list] of [['own',g.ownShots],['incoming',g.incoming]]){if(list.length>battleCounts[key])battleEffect={key,shot:list.at(-1),until:Date.now()+1800};battleCounts[key]=list.length;}}
 const effect=battleEffect&&battleEffect.until>Date.now()?battleEffect:null;
 const setup=g.status==='setup',finished=g.status==='finished',ready=g.ready[my],editing=setup&&!ready,turn=g.turn===my;
 const ownFleet=editing?ships.map(fleetCells):(g.ownFleet||[]),enemySunk=g.enemySunk||[];
 const sunkOwn=ownFleet.filter(s=>s.every(c=>g.incoming.some(hit=>hit.cell===c&&hit.hit))).length;
 const last=g.ownShots.at(-1),incoming=g.incoming.at(-1);
 const result=g.reason==='surrender'?'對局已結束 · 本局沒有獎勵':g.winner===my?'你贏了！漂亮的航程。':'航程完成，下次換你掌舵。';
 const headline=finished?result:setup?(ready?'艦隊已就位，等伴侶出航':'在海圖上藏好你的艦隊'):turn?'輪到你，選一格海域探索':'伴侶正在瞄準，稍等一下';
 const board=enemy=>Array.from({length:36},(_,cell)=>{const shots=enemy?g.ownShots:g.incoming,shot=shots.find(s=>s.cell===cell);const shipIndex=ownFleet.findIndex(s=>s.includes(cell));const sunk=enemy?enemySunk.some(s=>s.includes(cell)):ownFleet.some(s=>s.includes(cell)&&s.every(c=>g.incoming.some(h=>h.cell===c&&h.hit)));const revealed=enemy&&finished&&g.enemyBoard?.includes(cell);const mine=!enemy&&shipIndex>=0;
 const fresh=effect?.key===(enemy?'own':'incoming')&&effect.shot.cell===cell;
 const enabled=enemy?g.status==='playing'&&turn&&!shot&&!battlePending:editing&&!battlePending;
 const cls=[shot?(shot.hit?'hit':'miss'):'',mine||revealed?'ship':'',sunk?'sunk':'',fresh?'impact':'',mine&&editing&&shipIndex===fleetSelected?'selected-ship':''].filter(Boolean).join(' ');
 return `<button class="${cls}" ${enabled?'':'disabled'} ${enemy?`data-fire="${cell}"`:`data-deploy="${cell}"`} aria-label="${enemy?'對方':'我方'} ${seaCoord(cell)}${shot?(sunk?' 已擊沉':shot.hit?' 命中':' 落水'):mine?' 船艦':''}" ${mine&&editing?`aria-pressed="${shipIndex===fleetSelected}"`:''}><span class="cell-coordinate">${seaCoord(cell)}</span>${mine||revealed?'<span class="deck-piece" aria-hidden="true"></span>':''}${shot?`<span class="shot-marker" aria-hidden="true">${shot.hit?'✦':'·'}</span>`:''}${fresh?'<span class="impact-ring" aria-hidden="true"></span>':''}</button>`;}).join('');
 const fleetOverlay=enemy=>{
 const list=enemy?(finished&&g.enemyBoard?.length===7?[g.enemyBoard.slice(0,3),g.enemyBoard.slice(3,5),g.enemyBoard.slice(5,7)]:enemySunk):ownFleet;
 return '<div class="fleet-overlay" aria-hidden="true">'+list.map(cells=>{const start=Math.min(...cells),vertical=cells.length>1&&cells[1]-cells[0]===6,sunk=enemy?enemySunk.some(s=>s.includes(start)):cells.every(c=>g.incoming.some(s=>s.cell===c&&s.hit));return '<span class="chart-vessel '+(vertical?'vertical ':'')+(sunk?'sunken':'')+'" style="grid-column:'+(start%6+1)+' / span '+(vertical?1:cells.length)+';grid-row:'+(Math.floor(start/6)+1)+' / span '+(vertical?cells.length:1)+'">'+shipArt()+'</span>';}).join('')+'</div>';
 };
 const boardPanel=(enemy)=>`<section class="sea-panel ${enemy?'enemy-sea':'own-sea'}"><div class="sea-heading"><div><span class="naval-eyebrow">${enemy?'TARGET WATERS':'HOME FLEET'}</span><h3>${enemy?'對方海域':'我的海圖'}</h3></div><span class="fleet-count">${enemy?3-enemySunk.length:3-sunkOwn} / 3 艘</span></div><div class="sea-chart"><div class="chart-letters">${'ABCDEF'.split('').map(x=>`<span>${x}</span>`).join('')}</div><div class="chart-numbers">${[1,2,3,4,5,6].map(x=>`<span>${x}</span>`).join('')}</div><div class="board-stack"><div class="board naval-board">${board(enemy)}</div>${fleetOverlay(enemy)}</div></div><p class="sea-caption">${enemy?(setup?'迷霧中的艦隊，開戰後才能探索。':turn&&!finished?'點選一格射擊 · 每回合一次':'已探索 '+g.ownShots.length+' / 36 格'):(editing?'先選船，再點格子設定船首位置。':'命中 '+g.incoming.filter(s=>s.hit).length+' / 7 格船身')}</p></section>`;
 const deployment=editing?`<section class="fleet-dock"><div class="row space"><h3>你的三艘小船</h3><div class="dock-actions"><button id="rotate-fleet">旋轉方向</button><button id="random-fleet">隨機部署</button></div></div><div class="fleet-picker">${ships.map((s,i)=>`<button data-fleet="${i}" aria-pressed="${fleetSelected===i}">${shipArt()}<b>${fleetNames[i]}</b><small>${[3,2,2][i]} 格 · ${s.direction==='h'?'水平':'垂直'} · ${seaCoord(s.y*6+s.x)}</small></button>`).join('')}</div><div class="row space"><span id="fleet-validation" role="status" class="${fleetValid(ships)?'':'invalid'}">${fleetValid(ships)?'位置有效，準備好就出航。':'船艦重疊或超出邊界，請移動或旋轉。'}</span><button id="place-ships" class="primary" ${!fleetValid(ships)||battlePending?'disabled':''}>${battlePending?'正在部署…':'確認部署 · 出航'}</button></div></section>`:'';
 container.innerHTML=`<div class="naval-status ${turn&&!setup&&!finished?'your-turn':''} ${finished?'voyage-finished':''}" role="status"><span class="status-beacon"></span><div><strong>${headline}</strong><small>${finished?(g.reason==='surrender'?'隨時可以再約一局。':`金幣已入帳 +${g.winner===my?45:35} · 命中率 ${g.ownShots.length?Math.round(g.ownShots.filter(s=>s.hit).length/g.ownShots.length*100):0}%`):setup?'雙方確認部署後，由小晴先行。':'每次射擊都會換手，仔細觀察留下的線索。'}</small></div>${!setup?`<span class="shot-count">${g.ownShots.length+g.incoming.length}<small>次探索</small></span>`:''}</div>${!state.partner.online?'<div class="naval-offline">伴侶暫時離線，對局已保留，回來後可繼續。</div>':''}${deployment}<div class="board-area">${boardPanel(false)}${boardPanel(true)}</div><div class="naval-log" aria-live="polite"><div><small>你的最近一發</small><b>${last?`${seaCoord(last.cell)} · ${last.sunk?'擊沉一艘船！':last.hit?'命中船身':'落水，排除一格'}`:'等待第一個座標'}</b></div><div><small>伴侶的最近一發</small><b>${incoming?`${seaCoord(incoming.cell)} · ${incoming.sunk?'一艘船沉沒了':incoming.hit?'命中船身':'落水，安全度過'}`:'海面依然平靜'}</b></div></div><div class="naval-footer"><span>✦ 命中　· 落水　<span class="sunk-key">擊沉</span></span>${finished?'<button id="new-game" class="primary">再玩一局 →</button>':'<button id="surrender" class="quiet danger">結束這局</button>'}</div>${effect?`<div class="battle-announcement ${effect.shot.sunk?'is-sunk':''}" role="status">${effect.shot.sunk?'艦船沉沒':effect.shot.hit?'命中！':'水花濺起'}<small>${effect.key==='own'?'你的射擊':'伴侶的射擊'} · ${seaCoord(effect.shot.cell)}</small></div>`:''}`;
 container.querySelectorAll('[data-fleet]').forEach(b=>b.onclick=()=>{fleetSelected=+b.dataset.fleet;gameView();});
 container.querySelectorAll('[data-deploy]:not(:disabled)').forEach(b=>b.onclick=()=>{ships[fleetSelected]={...ships[fleetSelected],x:+b.dataset.deploy%6,y:Math.floor(+b.dataset.deploy/6)};gameView();});
 if($('rotate-fleet'))$('rotate-fleet').onclick=()=>{ships[fleetSelected].direction=ships[fleetSelected].direction==='h'?'v':'h';gameView();};
 if($('random-fleet'))$('random-fleet').onclick=()=>{ships=randomFleet();gameView();};
 if($('place-ships'))$('place-ships').onclick=()=>battleAction('game/place',{gameId:g.id,ships});
 container.querySelectorAll('[data-fire]:not(:disabled)').forEach(b=>b.onclick=()=>battleAction('game/fire',{gameId:g.id,cell:+b.dataset.fire}));
 if($('new-game'))$('new-game').onclick=()=>battleAction('game/new',{});
 if($('surrender'))$('surrender').onclick=()=>{if(confirm('結束本局會視為投降，雙方都不會獲得金幣。確定結束？'))battleAction('game/surrender',{gameId:g.id});};
}
