'use strict';
let dessertPending=false;
const dessertLabels={whisk:'雲朵攪拌',bake:'暖爐烘烤',decorate:'糖霜裝飾',teamwork:'默契分工',prank:'麵粉惡作劇',guard:'圍裙防守',rescue:'補救秘方'};
async function dessertAction(action,data={}){if(dessertPending)return;dessertPending=true;dessertView();try{await api(action,data);}catch(e){toast(e.message);}finally{dessertPending=false;if(view==='dessert')dessertView();}}
function dessertView(){
  title('甜點廚房大作戰','DESSERT DUEL');
  const g=state.dessert;
  if(!g){
    $('modal-content').innerHTML=`<div class="dessert-lobby"><section><span class="dessert-eyebrow">RETRO SWEET KITCHEN</span><h3>一起做甜點，偷偷來點小搗蛋。</h3><p>8 回合雙人行動卡。每回合兩人各選一張，等雙方都選好後一起結算。合作會提高甜點品質和共同銀行獎勵；惡作劇能衝個人分，但廚房太混亂會拉低成果。</p><ol class="dessert-rules"><li>料理卡讓甜點變精緻。</li><li>支援卡累積默契並補救失誤。</li><li>惡作劇可以得分，防守可以反制。</li><li>最後發個人金幣與共同銀行獎勵。</li></ol><button class="primary" id="dessert-start">開始營業</button></section><section class="dessert-shop"><div class="awning"></div><div class="counter"><i></i><i></i><i></i></div><div class="cake cake-a"></div><div class="cake cake-b"></div><div class="steam s1"></div><div class="steam s2"></div><div class="recipe-card">TODAY'S<br>SPECIAL</div></section></div>`;
    $('dessert-start').onclick=()=>dessertAction('dessert/new');return;
  }
  const finished=g.status==='finished', waiting=g.status==='playing'&&g.ownAction, partner=g.partnerReady, order=g.current||{};
  const scoreA=g.scores?.a||0,scoreB=g.scores?.b||0,total=Math.max(1,scoreA+scoreB),mine=state.user.id;
  const status=finished?`甜點完成 · ${g.memory?.text||''}`:waiting?(partner?'雙方都選好了，正在烘烤結算…':'已選好，等伴侶放入行動卡'):`第 ${g.round} / ${g.maxRounds} 回合 · ${order.name}`;
  const cards=(g.cards||[]).map(c=>`<button data-card="${c.id}" class="dessert-card card-${c.type}" ${finished||waiting||dessertPending?'disabled':''}><span>${c.icon}</span><b>${esc(c.name)}</b><small>${esc(c.description)}</small></button>`).join('');
  const log=(g.log||[]).slice().reverse().map(r=>`<article class="dessert-log-row"><span>ROUND ${r.round}</span><b>${esc(r.order)}</b><p>${esc((r.events||[]).join(' '))}</p><small>${state.user.id==='a'?'你':state.partner.name}：${dessertLabels[r.actions?.a]||''} · ${state.user.id==='b'?'你':state.partner.name}：${dessertLabels[r.actions?.b]||''}</small></article>`).join('');
  $('modal-content').innerHTML=`<div class="dessert-status ${finished?'finished':waiting?'waiting':''}"><div><span class="dessert-eyebrow">${finished?'SHOP CLOSED':waiting?'OVEN IS WORKING':'NOW BAKING'}</span><strong>${esc(status)}</strong><small>${finished?'共同銀行 +'+(g.rewards?.shared||0)+' · 你獲得 '+(g.rewards?.[mine]||0)+' 金幣':esc(order.hint||'照著食譜提示選卡，默契會更高。')}</small></div><div class="dessert-round">${finished?(g.memory?.grade||'A'):g.round}<small>${finished?'GRADE':'ROUND'}</small></div></div><div class="dessert-meter-row"><label>甜點品質 <b>${g.quality}</b><span><i style="width:${g.quality}%"></i></span></label><label>默契 <b>${g.harmony}</b><span><i style="width:${g.harmony}%"></i></span></label><label>混亂 <b>${g.chaos}</b><span class="chaos"><i style="width:${g.chaos/60*100}%"></i></span></label></div><div class="dessert-layout"><section class="dessert-stage ${finished?'stage-finished':''}"><div class="dessert-score"><b>你 ${mine==='a'?scoreA:scoreB}</b><div><span style="width:${mine==='a'?scoreA/total*100:scoreB/total*100}%"></span></div><b>${esc(state.partner.name)} ${mine==='a'?scoreB:scoreA}</b></div><div class="oven"><div class="oven-window"><i class="pastry"></i><i class="spark spark-a"></i><i class="spark spark-b"></i></div><div class="knobs"><i></i><i></i><i></i></div></div><div class="prep-table"><i class="bowl"></i><i class="berry"></i><i class="cream"></i><i class="flour"></i></div>${finished?`<div class="dessert-result"><b>${g.winner==='draw'?'平手':g.winner===mine?'你獲勝':'伴侶獲勝'}</b><small>${esc(g.memory?.text||'完成甜點')}</small></div>`:''}</section><section class="dessert-side"><h3>本回合行動卡</h3><div class="dessert-cards">${cards}</div><div class="dessert-ready"><span>你：${g.ownAction?dessertLabels[g.ownAction]:'尚未選擇'}</span><span>伴侶：${g.partnerReady?'已選好':'等待中'}</span></div>${finished?'<button id="dessert-new" class="primary">再開一局</button>':'<button id="dessert-surrender" class="quiet danger">收拾廚房</button>'}</section></div><section class="dessert-log"><h3>廚房回憶</h3>${log||'<p class="small">第一回合還沒結算。選好行動後，等伴侶一起揭曉。</p>'}</section>${g.log?.length&&!finished?'<div class="dessert-announcement">'+esc(g.log.at(-1).events?.[0]||'香氣升起來了')+'<small>ROUND '+g.log.at(-1).round+'</small></div>':''}`;
  document.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>dessertAction('dessert/play',{gameId:g.id,card:b.dataset.card}));
  $('dessert-new')?.addEventListener('click',()=>dessertAction('dessert/new'));
  $('dessert-surrender')?.addEventListener('click',()=>dessertAction('dessert/surrender',{gameId:g.id}));
}
const dessertRender=render;render=function(){if(view==='dessert')return dessertView();dessertRender();};
const dessertActivity=window.togetherBridge.activity;
window.togetherBridge.activity=(id,title,description)=>{if(id==='cooking')openView('dessert');else dessertActivity(id,title,description);};
